name: pg-migrate

services:
  db-old:
    image: docker.io/library/postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "dev"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h $$(hostname -i)" ]
      interval: 3s
      timeout: 15s
      retries: 10
    volumes:
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,Z
    networks:
      common:

  db-new:
    image: docker.io/library/postgres:18.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "dev"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h $$(hostname -i)" ]
      interval: 3s
      timeout: 15s
      retries: 10
    networks:
      common:

  pg-migrate:
    build:
      context: ./
      dockerfile: Containerfile
    command: [
      "--from-host", "db-old",
      "--from-port", "5432",
      "--from-user", "dev",
      "--from-pass", "dev",
      "--to-host", "db-new",
      "--to-port", "5432",
      "--to-user", "dev",
      "--to-pass", "dev",
      "--max-parallel", "4",
      "--exclude-table-data", "pdb1.table3",
      "--exclude-table-data", "pdb2.table*",
    ]
    depends_on:
      db-old:
        condition: service_healthy
      db-new:
        condition: service_healthy
    networks:
      common:

networks:
  common:
    driver: bridge
