name: pg-migrate

services:
  db-old:
    image: docker.io/library/postgres:9.5
    command: ["postgres", "-c", "max_connections=300", "-c", "max_wal_size=2GB", "-c", "checkpoint_timeout=10min"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "dev"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h $$(hostname -i)" ]
      interval: 3s
      timeout: 15s
      retries: 30
      start_period: 60s
    volumes:
      - ./.docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,Z
    networks:
      common:

  db-new:
    image: docker.io/library/postgres:18.4
    command: ["postgres", "-c", "max_connections=300"]
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "dev"
      POSTGRES_USER: "dev"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h $$(hostname -i)" ]
      interval: 3s
      timeout: 15s
      retries: 10
    networks:
      common:

  pg-migrate:
    build:
      context: ./
      dockerfile: Containerfile
    volumes:
      - ./config.toml:/config.toml:ro,Z
    command: [
      "--config", "/config.toml",
      "--from-host", "db-old",
      "--from-port", "5432",
      "--from-user", "dev",
      "--from-pass", "dev",
      "--to-host", "db-new",
      "--to-port", "5432",
      "--to-user", "dev",
      "--to-pass", "dev",
    ]
    depends_on:
      db-old:
        condition: service_healthy
      db-new:
        condition: service_healthy
    networks:
      common:

networks:
  common:
    driver: bridge
